import type { Metadata } from "next";
import { Roboto, Inter } from 'next/font/google';
import "./globals.css";
import Header from "@/components/header/header";
import NavBar from "@/components/navbar/navbar";
import { LifecycleCountsProvider} from "@/lib/service/lifecyclecounts-context";

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-[var(--background)]">
        <div className="app-layout flex min-h-screen w-full">
          <div className="flex-shrink-0 bg-[#52796f]">
            <NavBar/>
          </div>
          {/* Right side: Header + Main */}
          <div className="right-side-view flex flex-col flex-1 min-w-0">
            <LifecycleCountsProvider>
              <Header /> {/* full width of right side */}
              <main className="main-area flex-1 overflow-x-auto p-6">
                {children}
              </main>
            </LifecycleCountsProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
